### ISSUE TITLE
Missing translation on "Cancel" Button

### ISSUE THREAD

**Issue by nefft0n** [phyphox/phyphox-ios#11]
If a Bluetooth device has to be connected in an experiment in the iOS version, the connection window can be closed with a "Cancel" button. At least in the german version, there is no translation here ("Abbrechen" would be the translation).

Since the translation is available in other windows where an action can be canceled, i think this is not a translation issue but a coding issue.

**Comment by GTripathee** [comment]
Thank you for bringing up this issue. It has been resolved and you were right that it was not the translation but the coding issue. This update will be seen on the next release.
