### ISSUE TITLE
Use SPM

### ISSUE THREAD

**Issue by JonasGessner** [phyphox/phyphox-ios#2]
When I worked on this project Swift Package Manager did not exist yet and I didn't want to use CocoaPods. At this point my solution is pretty crappy compared to using SPM and I suggest moving all dependency management to SPM.

**Comment by Staacks** [comment]
Hi Jonas, good to see you! I guess you are by now on a different pay grade and I cannot lure you back with a student assistant position? ;)

I have not noticed SPM yet, but I will definitely look into it. Should not be too hard to switch.

**Comment by JonasGessner** [comment]
> Hi Jonas, good to see you! I guess you are by now on a different pay grade and I cannot lure you back with a student assistant position? ;)
> 
> I have not noticed SPM yet, but I will definitely look into it. Should not be too hard to switch.

It's all integrated in Xcode and easy to use, you just have to hope that all dependencies support SPM 😄

**Comment by Staacks** [comment]
Finally got around to do some house keeping including moving those dependencies over SPM that support it: e5b0daa43208452e0fd155e6a5edd300caf72a0b

**Comment by JonasGessner** [comment]
Cool!
